#!/bin/sh
# Builds rt.c into flat position-independent blobs and writes ../rt_<arch>.go
# with the blob and the offset of every exported rt_ function. The compiler
# must place a blob at a 64-byte aligned address.
set -eu
cd "$(dirname "$0")"
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

build() {
	goarch=$1 name=$2 target=$3 file=$4
	shift 4
	clang --target="$target" -Os -ffreestanding -fno-builtin -fno-math-errno -fPIC \
		-fno-stack-protector -fno-asynchronous-unwind-tables -fno-unwind-tables -fno-jump-tables \
		-ffunction-sections -Wall -Wextra -Werror "$@" -c rt.c -o "$tmp/$goarch.o"
	ld.lld -T blob.ld --no-dynamic-linker -static -e rt_init -o "$tmp/$goarch.elf" "$tmp/$goarch.o"
	if llvm-readelf -S "$tmp/$goarch.elf" | grep -Eq '\.(data|bss|got|sdata|sbss)'; then
		echo "rt: $goarch blob must not contain writable data or a GOT" >&2
		llvm-readelf -S "$tmp/$goarch.elf" >&2
		exit 1
	fi
	if llvm-readelf -r "$tmp/$goarch.elf" | grep -q 'R_'; then
		echo "rt: $goarch blob must not need relocations" >&2
		exit 1
	fi
	if [ "$goarch" = arm64 ] && llvm-objdump -d "$tmp/$goarch.elf" | grep -q 'adrp'; then
		echo "rt: arm64 blob must not use page-relative adrp" >&2
		exit 1
	fi
	llvm-objcopy -O binary --only-section=.text "$tmp/$goarch.elf" "$tmp/$goarch.bin"
	out=../rt_$file.go
	{
		echo '// Code generated by runtime/build.sh; DO NOT EDIT.'
		echo
		echo 'package main'
		echo
		echo "var rt${name}Syms = map[string]int{"
		llvm-nm "$tmp/$goarch.elf" | awk '$2 == "T" && $3 ~ /^rt_/ { printf "\t\"%s\": 0x%s,\n", $3, $1 }'
		echo '}'
		echo
		echo "var rt${name} = []byte(\"\" +"
		od -An -v -tx1 "$tmp/$goarch.bin" | tr -s ' \n' '  ' | awk '{
			for (i = 1; i <= NF; i++) {
				if ((i - 1) % 32 == 0) printf "\t\""
				printf "\\x%s", $i
				if (i % 32 == 0 || i == NF) printf "\"%s\n", (i == NF ? ")" : " +")
			}
		}'
	} > "$out"
	gofmt -w "$out"
}

build amd64 AMD64 x86_64-unknown-none-elf x86_64 -mno-red-zone
build arm64 ARM64 aarch64-unknown-none-elf aarch64 -mcmodel=tiny -ffixed-x18
build riscv64 RISCV64 riscv64-unknown-none-elf rv64 -march=rv64gc -mabi=lp64d -mcmodel=medany
