#!/bin/sh
# Builds num.c into flat position-independent blobs and writes ../numrt_<arch>.go.
# (Arch names avoid GOARCH file suffixes so every blob builds on every host.)
set -eu
cd "$(dirname "$0")"
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

build() {
	goarch=$1 name=$2 target=$3 file=$4
	shift 4
	clang --target="$target" -Os -ffreestanding -fno-builtin -fPIC -fvisibility=hidden \
		-fno-stack-protector -fno-asynchronous-unwind-tables -fno-unwind-tables -fno-jump-tables \
		-ffunction-sections "$@" -c num.c -o "$tmp/$goarch.o"
	ld.lld -T blob.ld --no-dynamic-linker -static -e tim_num -o "$tmp/$goarch.elf" "$tmp/$goarch.o"
	if llvm-readelf -S "$tmp/$goarch.elf" | grep -Eq '\.(data|bss|got)'; then
		echo "numrt: $goarch blob must not contain writable data or a GOT" >&2
		exit 1
	fi
	if [ "$goarch" = amd64 ] && llvm-objdump -d --no-show-raw-insn "$tmp/$goarch.elf" | grep -E '\(%rip\)' |
		grep -Ev '\s(movsd|movq|movl|movzbl|leaq|cvtsi2sd|cvttsd2si|ucomisd|comisd|addsd|subsd|mulsd|divsd|maxsd|minsd|andnpd|cmpq|cmpl|callq|jmp)\s' |
		grep -Eq '\s(movap|movdqa|and|or|xor|sub|add|mul|div|punpck|unpck|pshuf|shuf|max|min)[a-z]*\s'; then
		echo "numrt: blob uses 16-byte aligned constant loads; it must run at any alignment" >&2
		exit 1
	fi
	if [ "$goarch" = arm64 ] && llvm-objdump -d "$tmp/$goarch.elf" | grep -q 'adrp'; then
		echo "numrt: arm64 blob must not use page-relative adrp" >&2
		exit 1
	fi
	llvm-objcopy -O binary --only-section=.text "$tmp/$goarch.elf" "$tmp/$goarch.bin"
	entry=$(llvm-nm "$tmp/$goarch.elf" | awk '$3 == "tim_num" { print $1 }')
	out=../numrt_$file.go
	{
		echo '// Code generated by numrt/build.sh; DO NOT EDIT.'
		echo
		echo 'package main'
		echo
		echo "const numRuntime${name}Entry = 0x$entry"
		echo
		echo "var numRuntime${name} = []byte(\"\" +"
		od -An -v -tx1 "$tmp/$goarch.bin" | tr -s ' \n' '  ' | awk '{
			for (i = 1; i <= NF; i++) {
				if ((i - 1) % 32 == 0) printf "\t\""
				printf "\\x%s", $i
				if (i % 32 == 0 || i == NF) printf "\"%s\n", (i == NF ? ")" : " +")
			}
		}'
	} > "$out"
	gofmt -w "$out"
}

build amd64 AMD64 x86_64-unknown-none-elf x86_64 -mno-red-zone
build arm64 ARM64 aarch64-unknown-none-elf aarch64 -mcmodel=tiny -ffixed-x18
build riscv64 RISCV64 riscv64-unknown-none-elf rv64 -march=rv64gc -mabi=lp64d -mcmodel=medany
