#!/bin/sh
# Builds num.c into a flat position-independent blob and writes ../numrt_amd64.go.
set -eu
cd "$(dirname "$0")"
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

clang --target=x86_64-unknown-none-elf -Os -ffreestanding -fno-builtin -fPIC -fvisibility=hidden \
	-fno-stack-protector -fno-asynchronous-unwind-tables -fno-unwind-tables -fno-jump-tables \
	-mno-red-zone -ffunction-sections -c num.c -o "$tmp/num.o"
ld.lld -T blob.ld --no-dynamic-linker -static -e tim_num -o "$tmp/num.elf" "$tmp/num.o"
if llvm-readelf -S "$tmp/num.elf" | grep -Eq '\.(data|bss|got)'; then
	echo "numrt: blob must not contain writable data or a GOT" >&2
	exit 1
fi
if llvm-objdump -d --no-show-raw-insn "$tmp/num.elf" | grep -E '\(%rip\)' |
	grep -Ev '\s(movsd|movq|movl|movzbl|leaq|cvtsi2sd|cvttsd2si|ucomisd|comisd|addsd|subsd|mulsd|divsd|maxsd|minsd|andnpd|cmpq|cmpl|callq|jmp)\s' |
	grep -Eq '\s(movap|movdqa|and|or|xor|sub|add|mul|div|punpck|unpck|pshuf|shuf|max|min)[a-z]*\s'; then
	echo "numrt: blob uses 16-byte aligned constant loads; it must run at any alignment" >&2
	exit 1
fi
llvm-objcopy -O binary --only-section=.text "$tmp/num.elf" "$tmp/num.bin"
entry=$(llvm-nm "$tmp/num.elf" | awk '$3 == "tim_num" { print $1 }')

{
	echo '// Code generated by numrt/build.sh; DO NOT EDIT.'
	echo
	echo 'package main'
	echo
	echo "const numRuntimeAMD64Entry = 0x$entry"
	echo
	echo 'var numRuntimeAMD64 = []byte("" +'
	od -An -v -tx1 "$tmp/num.bin" | tr -s ' \n' '  ' | awk '{
		for (i = 1; i <= NF; i++) {
			if ((i - 1) % 32 == 0) printf "\t\""
			printf "\\x%s", $i
			if (i % 32 == 0 || i == NF) printf "\"%s\n", (i == NF ? ")" : " +")
		}
	}'
} > ../numrt_amd64.go
gofmt -w ../numrt_amd64.go
